language: python
python:
  - "3.7"
addons:
  apt:
    packages:
      - build-essential
      - libcap-dev
      - python-qt4
      - xvfb
install:
  - pip install -r requirements.txt
  - ln -s src pybitmessage  # tests environment
  - python setup.py install
script:
  - python checkdeps.py
  - src/bitmessagemain.py -t
  - python setup.py test
